require('core/options')
require('core/lazy')
require('core/appearence')
require('core/autocmds')
require('core/keymaps')
require('plugins/nvim-treesitter')
require('plugins/telescope')
require('plugins/zk')
